# Tests for the two machine learning model enpoints

###
POST http://localhost:5000/surgery-recovery/api/v1.0/predict_intent HTTP/1.1
content-type: application/json

{
    "input": "When can I take my bandages off?"
}

###
POST http://localhost:5000/surgery-recovery/api/v1.0/random_reply HTTP/1.1
content-type: application/json

{
    "tag": "greeting"
}
